Portfolio: finish mobile version
Ouail-01/Portfolio_project pull request #2
Opened 2022-12-02 22:18 UTC by Ouail-01

2022-12-02 23:06 UTC, Yerimah requested changes
# STATUS: INVALID REQUEST 🔴 

Hi @Ouail-01 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![for invalid pul request](https://user-images.githubusercontent.com/71140133/205404178-098607b4-8113-4476-8a21-6f728243b25d.gif)

## Invalid Code Review Request

You have submitted a project that doesn't contain a short descriptive summary of the changes introduced in the pull request. it is important to make your repo look professional.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-03 00:50 UTC, joskalenda requested changes
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @Ouail-01 , |
|Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there! |
| <img src="https://media1.giphy.com/media/TZNLFZh5TeNRJKQXzm/giphy.gif"/> |

## Highlights

- [ ]...Good design✅ 
- [ ]...Well structured code ✅ 
- [ ]...Green linters check✅ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 00:50 UTC, joskalenda commented on index.html
> +                <hr>
- [ ] No comment @Ouail-01 , you have done an amazing job, I really appreciate it, your code is well structured, however, you have some few changes to do in the design before you project get approved, let's take a look them  🤗

<img width="700" alt="oua1" src="https://user-images.githubusercontent.com/77843050/205413013-ffb3b563-6139-443b-95c5-cdce9d971911.png">

- [ ] As highlighted, let me be more explicit.... at the first look on the background color of your app compared to the figma at the right, am sure to remark a difference between them, please make sure they match same as per the requirement
- [ ] the `multi-post` title, please use the same color and font as per the requirement.
- [ ] same as the technologies sections, kindly modify them to match the same design as in the figma

2022-12-03 00:50 UTC, joskalenda commented on index.html
> +                    <br> don’t hestiate to contact me.</p>
- [ ] Same as here, please do these few changes, remember, it is recommanded you stcik on the figma design as much as posible by using the same `color, padding, font,..` all properties as used in the orignal design please.
- [ ] All your cards backgrounds are diffrent from the original design, kindly make sure you modify everything.
<img width="672" alt="ouai2" src="https://user-images.githubusercontent.com/77843050/205413612-e51c1283-ec51-4055-b8b5-cde637475460.png">

2022-12-03 00:50 UTC, joskalenda commented on index.html
> +                    </ul>
- [ ] Check this out, I would suggest you follow the design guidlines and update everything to match the correct figma template
<img width="626" alt="fram" src="https://user-images.githubusercontent.com/77843050/205413923-5fe8c9d8-80d5-47d7-8e17-c1d5e96f717b.png">

2022-12-03 14:05 UTC, amejid approved these changes
Hi @Ouail-01, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights
- Descriptive PR :heavy_check_mark: 
- Good UI design :fire: 
- Correct use of Github flow :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 15:59 UTC, merged